site_name: Fiware-iotagent-lwm2m
site_url: https://fiware-iotagent-lwm2m.readthedocs.io
repo_url: https://github.com/telefonicaid/lightweightm2m-iotagent
site_description: IoT Agent LWM2M (CoAP/UDP transport) Documentation
docs_dir: docs
site_dir: html
edit_uri: edit/master/docs/
markdown_extensions: [toc,fenced_code]
use_directory_urls: false
theme: readthedocs
extra_css: ["https://fiware.org/style/fiware_readthedocs.css", "https://fiware.org/style/fiware_readthedocs_iot.css"]
pages:
  - 'Home': 'index.md'
  - 'User & Programmers Manual': 
    - 'Intro & Development guide': 'userGuide.md'
    - 'API Walkthrough & Device provisioning': 'deviceProvisioning.md'
    - 'Operation with Static configuration': 'staticConfiguration.md'
    - 'Operation with Provisioning configuration': 'configurationProvisioning.md'
  - 'Installation & Administration Manual': 'administrationGuide.md'
